### ISSUE TITLE
Multiple compatibility issues with cordova-plugin-file

### ISSUE THREAD

**Issue by arivera-skycred** [Donaldcwl/browser-image-compression#11]
First, thank you for the plugin. It's been working great so far until we added cordova-plugin-file to our solution.

It appears that the new types for `File` and `FileReader` don't work with this plugin.

I am working on fixes that will be backwards compatible with non-cordova implementations and will submit a PR when I have it working. 

Cheers!

**Comment by Donaldcwl** [comment]
#12 PR merged, I will release a new version soon. Thanks.

**Comment by Donaldcwl** [comment]
@arivera-skycred 
I have made some modifications so that the tests will pass.
I may need your help to verify it, please refer to #12.
Thanks.

**Comment by arivera-skycred** [comment]
> @arivera-skycred
> I have made some modifications so that the tests will pass.
> I may need your help to test it with your cordova environment, please refer to #12.
> Thanks.

Sure thing. I'll take a look.
