### ISSUE TITLE
[iOS Safari] White Picture if the file size is over 30 MB 

### ISSUE THREAD

**Issue by Frans-L** [Donaldcwl/browser-image-compression#116]
## Problem

Uploading pictures over 30 MB will lead to a full white picture with iPhone 12 Safari. 

![image](https://user-images.githubusercontent.com/29607206/130793882-b2539ffa-cbd7-48e0-8a91-8a214f9f63e3.png)

## Demo

The test PNG image can be downloaded from [here]( https://sample-videos.com/download-sample-png-image.php). The result can be tested in the[ demo site](https://donaldcwl.github.io/browser-image-compression/example/basic.html).

The issue probably exists in all iOS devices. Safari in macOS works.  

## Possible Reason 

The issue might be related that iOS Safari may not handle properly images/videos over 30 MB. I couldn't find any proper source for this except this [release note](https://developer.apple.com/safari/technology-preview/release-notes/) bullet point: 

![image](https://user-images.githubusercontent.com/29607206/130794143-39f29d12-22ef-486c-a81a-22f049765cf9.png)

## Expected Behaviour

The image should be resized normally. If the problem cannot be fixed because of technical limitations, the function should throw an error.

**Comment by marthee** [comment]
I'm experiencing the same issue with version `1.0.15`. `imageCompression` seemingly succeeds, but the image result is all black and I see this warning in the browser:
> Canvas area exceeds the maximum limit (width * height > 16777216).

I read this [[https://github.com/Donaldcwl/browser-image-compression#caveat](https://github.com/Donaldcwl/browser-image-compression#caveat)] part of the documentation as it should be handled. And if not possible, I agree it should throw an error.

**Comment by Donaldcwl** [comment]
This issue is fixed in version 1.0.16.
Thanks for your contributions.
