### ISSUE TITLE
Transparent PNG -> jpeg shows black background.

### ISSUE THREAD

**Issue by zehawki** [Donaldcwl/browser-image-compression#119]
Transparent PNG -> jpeg shows black background.

Should be white, thats the accepted approach for such conversion.

I see this happening with any transparent PNG, when converted to jpeg shows black. Eg https://www.transparentpng.com/download/happy-st-patricks-day-_34433.html produces:

![image](https://user-images.githubusercontent.com/8095144/132966007-768ada02-9112-423c-8531-6ed08b212991.png)

**Comment by Donaldcwl** [comment]
For a transparent png file with jpeg file extension, the previous version produces a black background.
In version 1.0.16, the new behavior will result in white background.
Thanks.

**Comment by nikkimoreaux** [comment]
Hi! Great little utility thank you! Just a suggestion, white background should always apply to PNG > JPEG conversions; currently v1.0.16 doesn't use white background with the fileType: 'image/jpeg' option. Have a nice day!

**Comment by Donaldcwl** [comment]
@nikkimoreaux Will apply this in the next version, thanks!!
