### ISSUE TITLE
Orientate error when compression

### ISSUE THREAD

**Issue by quangthienit1994** [Donaldcwl/browser-image-compression#126]
When compressing an image on IOS ( my case ios 15 ) the orientate auto make vertical become horizontal and image has been cropped, 
![image](https://user-images.githubusercontent.com/22471650/142967646-1be5e8e7-2cb1-48d8-a1b0-912e1a7af5fd.png)

**Comment by angelynats** [comment]
Still have the same bug in v1.0.17

**Comment by Donaldcwl** [comment]
Please provide the image, the device you use, the browser version and the steps to reproduce.

**Comment by quangthienit1994** [comment]
@Donaldcwl Version using: "browser-image-compression": "^1.0.12"
The problem is only on IOS, I check IPhone 6 (ios 12) and Iphone Xr (ios 15): the same issues

**Comment by Donaldcwl** [comment]
> @Donaldcwl Version using: "browser-image-compression": "^1.0.12" The problem is only on IOS, I check IPhone 6 (ios 12) and Iphone Xr (ios 15): the same issues

The version in package.json file does not necessarily be the installed version according to NPM. Please console.log the version to see the actual version you are using:

**Comment by AreebKhan619** [comment]
> > @Donaldcwl Version using: "browser-image-compression": "^1.0.12" The problem is only on IOS, I check IPhone 6 (ios 12) and Iphone Xr (ios 15): the same issues
> 
> The version in package.json file does not necessarily be the installed version according to NPM. Please console.log the version to see the actual version you are using: `console.log('imageCompression version', imageCompression.version)`

I'm having the same issue. After logging it using `imageCompression.version`, I'm getting the version as 1.0.14 (which is the same as indicated by my `package.json` file).

**Comment by Donaldcwl** [comment]
> > > @Donaldcwl Version using: "browser-image-compression": "^1.0.12" The problem is only on IOS, I check IPhone 6 (ios 12) and Iphone Xr (ios 15): the same issues
> > 
> > 
> > The version in package.json file does not necessarily be the installed version according to NPM. Please console.log the version to see the actual version you are using: `console.log('imageCompression version', imageCompression.version)`
> 
> I'm having the same issue. After logging it using `imageCompression.version`, I'm getting the version as 1.0.14 (which is the same as indicated by my `package.json` file).

Please upgrade to version 1.0.17 and try again.
