### ISSUE TITLE
[feature request] keep the same width and height, and reduce the quality only

### ISSUE THREAD

**Issue by GeekaholicLin** [Donaldcwl/browser-image-compression#127]
Thanks for the awesome library for the image compression!

I noticed that the width/height of the image will be reduced to meet the maxSizeMB. 

Is it possible to provide the option to keep the same width and height of the original image file and reduce the quality only?

https://github.com/Donaldcwl/browser-image-compression/blob/master/lib/image-compression.js#L95-L96

**Comment by fsuk** [comment]
Not a proper solution but this is what I have come up with. Basically after resizing the image to the max width/height I get the size of the image in MB, then multiply that by the quality factor (0-1) to get a new max file size which I then call compress a second time with.

```
 const resizeOptions = {
      maxWidthOrHeight: maxWidthHeight,
      useWebWorker: true,
      fileType: this.fileType,
      maxIteration: 10
    }
    
    let origImage = await imageCompression.getFilefromDataUrl(dataUrl, fileName);
    const origFileSize = origImage.size;
    let compressedImage = await imageCompression(origImage, resizeOptions);
    fileSize = compressedImage.size;

    let qualityMaxSizeMB = (fileSize / 1024 / 1024) * quality //0.00-1.00
    const compressOptions = {
      maxWidthOrHeight: maxWidthHeight,
      maxSizeMB: qualityMaxSizeMB,
      useWebWorker: true,
      fileType: this.fileType,
      maxIteration: 10
    }

    compressedImage = await imageCompression(origImage, compressOptions);
    fileSize = compressedImage.size;

    dataUrl = await imageCompression.getDataUrlFromFile(compressedImage);
```
