### ISSUE TITLE
Black Image on Image Compression

### ISSUE THREAD

**Issue by amusandhu** [Donaldcwl/browser-image-compression#130]
While compressing multiple images the code results in a Black Images for few of them and for others it results the compressed image. 
I am using V1.0.16 and this issue is still not fixed

**Comment by Donaldcwl** [comment]
Please upgrade to the latest version v1.0.17 and try again.

If the issue still exist, please provide the images, the device you use, the browser version and the steps to reproduce.

**Comment by jarechiga11** [comment]
While v1.0.17 no longer shows black images, some images now just result in a blank white image. I've been able to reproduce it by using this image (http://mediafiles.allaboutsymbian.com/808/zeiss/f.jpg) in your demo page.
![img-test](https://user-images.githubusercontent.com/9142381/144286777-11e9111c-7b73-46ed-bb01-abf2dbb7aa6d.png)

**Comment by Donaldcwl** [comment]
@jarechiga11 It works fine when I test with your image. May I know which OS(Mac/Window), version, browser version are you using? Is there any console log?

**Comment by Sceat** [comment]
I have the problem when using the code from an iphone, while on the desktop browser it works

**Comment by tkmin** [comment]
@Sceat did you resolve this issue?

@Donaldcwl I tried both "^v1.0.17" & "^2.0.0"

on some iPhone, compressing image for first try on page, turns blank white image
but on next tries on same page, image does not turns blank white.

device info
model: iphone xs max
IOS version: 15.5
browser: chrome & safari

----

my snippet

import imageCompression from 'browser-image-compression';
...
await imageCompression(image, { maxSizeMB: 1, maxWidthOrHeight: 800 });

**Comment by EastblueOkay** [comment]
I had the same issue on an IPhone (feedback from  user).
Even if the canvas-size is used to judge in advance.

**Comment by GurpreetCareMonitor** [comment]
This issue still exist. 
There is no resolution for this ticket but ticket is closed.

**Comment by Donaldcwl** [comment]
@GurpreetCareMonitor 
Which version of the browser-image-compression tool are you currently using? 
Please provide me with information regarding your device and browser, as well as the associated image file that you are compressing. 
This information is necessary for me to effectively debug any issues you may be experiencing.

**Comment by GurpreetCareMonitor** [comment]
we are using our web view in a mobile app, that is working perfectly in android but for iphone and ipad it is making image blank.

application version I am using 2.0.0
but i also tested latest 2.0.2 
but still issue persist.
image link: https://upload.wikimedia.org/wikipedia/commons/2/2d/Snake_River_%285mb%29.jpg

our app use [flutter](https://pub.dev/packages/webview_flutter) to render web view:
behind the Sean it use : 
iphone/ipad: https://developer.apple.com/documentation/webkit/wkwebview
android: https://developer.android.com/reference/android/webkit/WebView

**Comment by Donaldcwl** [comment]
@GurpreetCareMonitor 
Can you provide the user agent and canvas size of the web view browser that gives black image?

You can open the following websites inside the web view and send the results here.

Canvas size:
https://jsbin.com/megedep/1
User agent:
https://www.whatismybrowser.com/detect/what-is-my-user-agent/

**Comment by GurpreetCareMonitor** [comment]
I try with this in webview:
https://donaldcwl.github.io/browser-image-compression/example/basic.html

but still getting same issue with ipad and iphone

**Comment by Donaldcwl** [comment]
@GurpreetCareMonitor
Can you provide the user agent and canvas size of the web view browser that gives black image?

You can open the following websites inside the web view and send the results here.

Canvas size:
https://jsbin.com/megedep/1
User agent:
https://www.whatismybrowser.com/detect/what-is-my-user-agent/

**Comment by GurpreetCareMonitor** [comment]
@Donaldcwl 
as asked, It tested those and find:

 -  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36'
 - 
<img width="336" alt="MicrosoftTeams-image (6)" src="https://user-images.githubusercontent.com/91180929/225533070-7b2d432d-dcd7-4a67-942d-94faba62046f.png">
<img width="309" alt="MicrosoftTeams-image (8)" src="https://user-images.githubusercontent.com/91180929/225533082-0372503d-1ff9-415b-b43d-a30bf347c487.png">
<img width="314" alt="MicrosoftTeams-image (7)" src="https://user-images.githubusercontent.com/91180929/225533088-0e452013-190e-42e4-ae28-1d8241f3d5d3.png">


 -

**Comment by Donaldcwl** [comment]
@GurpreetCareMonitor Your Webview on iPhone has a desktop user agent so this library assumes a large canvas supported size. Please set the user agent to a correct one such as `Mozilla/5.0 (iPhone; CPU iPhone OS 16_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Mobile/15E148 Safari/604.1`
