### ISSUE TITLE
Losing EXIF information [QUESTION]

### ISSUE THREAD

**Issue by alebrozzoamz** [Donaldcwl/browser-image-compression#131]
When I try the library using `https://donaldcwl.github.io/browser-image-compression/example/basic.html` with the default parameter values, the image I upload gets properly resized and shown in the proper orientation, however the EXIF information is lost. Is this expected behaviour?

**Comment by Donaldcwl** [comment]
Yes, this is expected, the EXIF information is not preserved such as camera and focal length.
