### ISSUE TITLE
Cannot select image from Gdrive

### ISSUE THREAD

**Issue by ekobayu** [Donaldcwl/browser-image-compression#135]
Hello, I try select image from google drive in my phone but the browser-image-compression plugin cannot compress the file. I try using png, jpg and jpeg but all it's failed. Any suggestion ? Thanks

**Comment by Donaldcwl** [comment]
This is a bug with Android Chrome, please refer to: https://bugs.chromium.org/p/chromium/issues/detail?id=1063576
A workable solution is to reconstruct the File object:
```
<input
          type="file"
          accept="image/*"
          onchange="compressImage(event);"
/>
<script>
async function compressImage(event) {
  const file = event.target.files[0];
  const buffer = await file.arrayBuffer();
  const imageFile= new File([buffer], file.name, { type: file.type });
  const compressedFile = await imageCompression(imageFile, options);
  // ...
}
</script>
```

**Comment by ekobayu** [comment]
> This is a bug with Android Chrome, please refer to: https://bugs.chromium.org/p/chromium/issues/detail?id=1063576 A workable solution is to reconstruct the File object:
> 
> ```
> <body>
>     <input type="file" accept="image/*" onchange="compressImage(event);" />
> </body>
> <script>
> async function compressImage(event) {
>   const originalFile = event.target.files[0];
>   const buffer = await originalFile.arrayBuffer();
>   const imageFile= new File([buffer], file.name, { type: file.type });
>   const compressedFile = await imageCompression(imageFile, options);
>   // ...
> }
> </script>
> ```

Thanks bro, it's works!

**Comment by nine-zet** [comment]
> This is a bug with Android Chrome, please refer to: https://bugs.chromium.org/p/chromium/issues/detail?id=1063576 A workable solution is to reconstruct the File object:
> 
> <body>
>     <input type="file" accept="image/*" onchange="compressImage(event);" />
> </body>
> <script>
> async function compressImage(event) {
>   const originalFile = event.target.files[0];
>   const buffer = await originalFile.arrayBuffer();
>   const imageFile= new File([buffer], file.name, { type: file.type });
>   const compressedFile = await imageCompression(imageFile, options);
>   // ...
> }
> </script>

The same symptoms occurred in Android Webview and it works in the same way. Thx!!!
