### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by LongLiveTheDev** [Donaldcwl/browser-image-compression#136]
I got this error after just imported this library into my project.
"next": "12.0.7",
"browser-image-compression": "^1.0.17",
![image](https://user-images.githubusercontent.com/75295620/148547356-603e691f-d460-4c1a-8ad6-e96db47bc1ef.png)

**Comment by Donaldcwl** [comment]
You may need to exclude node_modules in your Webpack config.
You can refer to https://stackoverflow.com/a/35820388
