### ISSUE TITLE
Image is not being compressed according maxSizeMB given.

### ISSUE THREAD

**Issue by kamranblueeast** [Donaldcwl/browser-image-compression#137]
Hi all,
I am using browser-image-compression for image compression.
const options: Options = { 
  maxSizeMB: number,          // (default: Number.POSITIVE_INFINITY)
}|
According to options I am providing maxSizeMB=2MB.
On Uploading an image of like 9MB, the package is compressing the image to more than 2MB regarding that I have already provided maxSize to 2MB.
Is the some thing with image size or any thing else.
Any Suggestions will be appreciated.
Thanks

**Comment by Donaldcwl** [comment]
This library uses an iterative approach to compress images.
The image size is reduced after each iteration. Default iteration is 10 times.

It is possible that in some marginal cases, the image is still larger than the maxSizeMB after the process.

You can put additional config to increase the number of iterations:
```javascript
const options = {
    maxSizeMB: 2,
    maxIteration: 30
  }
```
