### ISSUE TITLE
GET data: net::ERR_INVALID_URL when I try to compress an image from android camera

### ISSUE THREAD

**Issue by giacomok** [Donaldcwl/browser-image-compression#146]
Hi,  
I have this code to compress image get from android camera:

    imageCompression(file, {
           //maxSizeMB: 1,
           maxWidthOrHeight: 2400,
           useWebWorker: true,
           initialQuality: 0.8,
     })
     .then(function (result) {});

`file` is an html file element
It works when I get an image from gallery. I get this error when I get image from android camera:

    GET data: net::ERR_INVALID_URL
    Image (async) |   |  
    -- | -- | --
      | (anonymous) | @ | utils.js:131
      | loadImage | @ | utils.js:127
      | (anonymous) | @ | utils.js:255

Do you think its an android permission problem, or its about this package?

**Comment by Donaldcwl** [comment]
@giacomok Did you try https://donaldcwl.github.io/browser-image-compression/example/basic.html ?

I couldn't reproduce this issue. Can you provide more details? Such as the image file, Android version, and browser version.

**Comment by giacomok** [comment]
@Donaldcwl thanks for the response, I solved.

The problem was not this library, but the android code.
