### ISSUE TITLE
The file given is not an instance of Blob or File with v2.0.0 on Next.js

### ISSUE THREAD

**Issue by maxproske** [Donaldcwl/browser-image-compression#147]
As of v2.0.0, your Next.js example appears to only work when you start Next.js in development mode, not production. Could this be related to core-js being dropped?

The docs say this [polyfill is for IE only](https://github.com/Donaldcwl/browser-image-compression#ie-support), but this issue affects Next.js on the latest version of Chrome, Firefox, and Safari.

`yarn dev`

![Screenshot from 2022-04-29 11-12-18](https://user-images.githubusercontent.com/14317828/166000023-0b1c0a50-a72e-4852-b118-023582f57303.png)

`yarn start`

![Screenshot from 2022-04-29 10-53-06](https://user-images.githubusercontent.com/14317828/165998976-f14db66a-c284-4ed7-914d-6aaa2258f2fb.png)

Here's a temporary fix for anyone looking for it:
```
yarn add browser-image-compression@1.0.13 --exact
```

**Comment by Donaldcwl** [comment]
@maxproske I couldn't reproduce this issue. Can you provide more details? Such as the image file, OS platform, and browser version.

You may also try to run again `yarn build` followed by `yarn start`. It works for me on Windows 10 Chrome 100.0.4896.88 with both PNG and JPG file.

**Comment by tom555my** [comment]
@maxproske I am having the same issue. 

Please find the following detail
OS: MacOS 12.3.1
Chrome: 102.0.5005.115

The image
![cute](https://user-images.githubusercontent.com/19559068/175802614-19836e18-01ff-4a7d-9a70-6927d8aeec46.jpeg)

**Comment by Donaldcwl** [comment]
@tom555my Here is the result of your image using the production mode of the example Nextjs app (https://github.com/Donaldcwl/browser-image-compression/tree/master/example/Nextjs%20App)
![image](https://user-images.githubusercontent.com/11781337/175805733-418f3b9a-837d-4cb6-aaa1-bff9efaaba6d.png)

I tested on both Win and MacOS Chrome.
Could you provide more information about the issues you faced?

**Comment by 3c1u** [comment]
I faced with the exact same issue. This might be related to the `swcMinify` option, which is available in newer Next.js versions ([details](https://nextjs.org/docs/advanced-features/compiler#minification)). With `swcMinify`, the production build breaks and `browser-image-compression` refuses to output compressed images. If I set `swcMinify` to `false`, this error disappears.

I also confirmed that the example is not broken with/without newer Next.js versions, as `swcMinify` seems to be not enabled by default.

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/298748/175931470-35f76663-2121-418b-a7bf-0599ee348ad5.png">

**Comment by Donaldcwl** [comment]
@3c1u 
I just tested browser-image-compression@2.0.0 on react@18.2.0, next@12.2.5 with swcMinify enable (true). I can't reproduce the issue. Could you share your source code that has the issue?

The nextjs source code I tested can be found here: https://github.com/Donaldcwl/browser-image-compression/tree/master/example/Nextjs%20App
