### ISSUE TITLE
Firefox: compression in Web Worker fails

### ISSUE THREAD

**Issue by RickStanley** [Donaldcwl/browser-image-compression#15]
When trying to use the lib in Firefox (67.0.1 (64-Bit) or Dev. Edition: 68.0b8 (64-Bit)) it yields: "Run compression in web worker failed: document is not defined , fall back to main thread"

**Comment by Donaldcwl** [comment]
@RickStanley 
This is not an issue beccause Firefox do not currently support "OffscreenCanvas" API which is required for compression to work in web worker (reference: https://caniuse.com/#feat=offscreencanvas), so the current behavior in Firefox is expected to be fall back to main thread.
