### ISSUE TITLE
"globalThis is not defined" even include core-js

### ISSUE THREAD

**Issue by taoliujun** [Donaldcwl/browser-image-compression#151]
I know `globalThis is not defined` error because it worked in browser like chrome > 70. so i set browserlistrc below.

`
> 0.5% in CN
android >= 7
chrome >= 60
ios >= 11
`

there are some code about `globalThis` in bundle core-js file ([core-js file](https://h5static.dewu.com/loan-h5/client/static/js/vendor.c68c7480.chunk.js)). but still error above. anyone can help me ?

**Comment by Donaldcwl** [comment]
@taoliujun Which version of the lib are you using? Do you still have the problem now?

**Comment by zloirock** [comment]
@Donaldcwl https://github.com/zloirock/core-js/issues/1089
