### ISSUE TITLE
suffix lost!!!

### ISSUE THREAD

**Issue by XAihan** [Donaldcwl/browser-image-compression#159]
When you compress it,The file suffix is missing.but i need it.Because the server needs this thing.Is there any way to keep it?

**Comment by Donaldcwl** [comment]
May I know what you mean by the file suffix?

**Comment by XAihan** [comment]
![image](https://user-images.githubusercontent.com/56574869/190963087-6728998b-4072-40eb-a9a8-fc104c866927.png)

like this. 

filepath: 
"/var/folders/vc/zkpz6wr15z14ln1z1rzy59yw0000gp/T/egg-multipart-tmp/node-egg/2022/09/19/14/d28b2e6d-24a1-4b3b-a427-a678153de8d0"

If I don't compress it：
![image](https://user-images.githubusercontent.com/56574869/190963338-e282a512-cb1d-4003-8f81-794e3a658180.png)
filepath: 
"/var/folders/vc/zkpz6wr15z14ln1z1rzy59yw0000gp/T/egg-multipart-tmp/node-egg/2022/09/19/14/49744730-7b75-40d1-96ff-b4b25867d47f.jpg"

This is the data information received at the Node back end.

**Comment by XAihan** [comment]
This is because the server needs to perform type verification, and because of the project itself, only the file suffix of filepath can be used for verification. So the absence of this would be very troubling to me.
Is there a way to solve this problem?

**Comment by XAihan** [comment]
I found out what the problem is. This is because the blob file is generated after compression. Filename defaults to blob when we upload. There is no suffix. So the corresponding filepath also has no suffix.

![image](https://user-images.githubusercontent.com/56574869/190979578-1abffcac-a497-4c59-9031-88155483a09b.png)

Solution: Change filename while generating blob Or rename it at upload time.

`
const forms = new FormData();
file = await handleCompressFile(file);
forms.append('data', file,'a.png');
`

<img width="589" alt="image" src="https://user-images.githubusercontent.com/56574869/190981038-1828738f-65b4-4c5c-b9f7-c0bfc1851270.png">
![image](https://user-images.githubusercontent.com/56574869/190981178-11a0e5f2-2548-40c8-8933-328ddea8d8f2.png)


If you do not set the blob name:
<img width="659" alt="image" src="https://user-images.githubusercontent.com/56574869/190981269-6432671e-e961-457b-9bb6-5ec442cc153e.png">
![image](https://user-images.githubusercontent.com/56574869/190981445-93ac7b72-a957-4a70-a8eb-1dd584da8a95.png)

**Comment by XAihan** [comment]
Perhaps the author could modify his filename directly while generating the blob. CanvasToFile in utils.js. There is a file conversion after BLOb generation.
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/56574869/190984667-90d4ca7d-bbcc-4ed5-9848-163daf210bc0.png">

Do a file conversion before the return file.
```
   const file = new window.File([blob],'a.png')
   // Or
   const file = new File([blob],'a.png')
```
The specific environmental judgment needs to be refined by the author.

**Comment by Donaldcwl** [comment]
@XAihan Thanks for your thorough investigation.
Safari has an issue with the File constructor not being able to POST in FormData (see #8, and https://bugs.webkit.org/show_bug.cgi?id=165081). So Blob is used instead.

You will have to put the filename params to the form data, please check out the following snippets:
```const options = {...}
const compressedFile = await imageCompression(file, options);
const form = new FormData();
form.append('image', compressedFile, compressedFile.name);
```
