### ISSUE TITLE
Unable to use the package in react when installing using npm

### ISSUE THREAD

**Issue by vinayedadan** [Donaldcwl/browser-image-compression#16]
Hi,
I tried installing the package in my react project using npm.
I used ES6 import. When I tried to console the imageCompression object, the output is displayed as a function.

Code is
"import imageCompression from 'browser-image-compression';
console.log(imageCompression)"

output is
"/static/media/browser-image-compression.9d2e921a.mjs"

the error I am getting is
"TypeError: __WEBPACK_IMPORTED_MODULE_1_browser_image_compression___default(...) is not a function"

**Comment by Donaldcwl** [comment]
@vinayedadan There may be some issues in your webpack setup.
To demonstrate the functionality of the package with React, I have created a demo on CodeSandbox, you may have a look at it here:
https://codesandbox.io/s/dq1j2

**Comment by Donaldcwl** [comment]
closed because of inactivity

**Comment by NileshP987** [comment]
> @vinayedadan There may be some issues in your webpack setup.
> To demonstrate the functionality of the package with React, I have created a demo on CodeSandbox, you may have a look at it here:
> https://codesandbox.io/s/dq1j2

I have seen this link of yours but in my system still getting "TypeError: __WEBPACK_IMPORTED_MODULE_1_browser_image_compression___default(...) is not a function" this issue
