### ISSUE TITLE
Is there a way to compress a base64 content instead of a file

### ISSUE THREAD

**Issue by Jalil-Irfan** [Donaldcwl/browser-image-compression#162]
I have a base64 content which i receive after the user crops and saves a picture in my angular app. 
i only have it as a base64 content instead of a File. 
Now i have to compress this file to 20kb or less and make sure the compressed file doesnt exceed 20kb size.
how do i do this 
Do i have to convert the base64 to a file then compress and again change it to base64?

**Comment by Donaldcwl** [comment]
You will have to convert the base64 to a file `file = await imageCompression.getFilefromDataUrl(base64String)`,
then compress `compressedFile = await imageCompression(file, options)`,
and change it back to base64 `base64String = await imageCompression.getDataUrlFromFile(compressedFile)`.
