### ISSUE TITLE
Keep Metadata

### ISSUE THREAD

**Issue by mwc2016** [Donaldcwl/browser-image-compression#164]
Might I know that how to keep the metadata during compression image

**Comment by sscholle** [comment]
like the 'lastModified' date?

**Comment by mwc2016** [comment]
> like the 'lastModified' date?

Yup, like below information

<img width="266" alt="Screenshot 2023-02-09 at 12 59 20 PM" src="https://user-images.githubusercontent.com/61489013/217722230-f0b076f5-16ef-46d8-9be5-6c9076f9e7cb.png">

**Comment by Donaldcwl** [comment]
added option `preserveExif` in v2.0.1 to enabled this feature
e.g.,
```javascript
const options = {
  maxSizeMB: 1,
  maxWidthOrHeight: 1920,
  useWebWorker: true,
  preserveExif: true,
}
try {
  const compressedFile = await imageCompression(imageFile, options);
  console.log('compressedFile instanceof Blob', compressedFile instanceof Blob); // true
  console.log(`compressedFile size ${compressedFile.size / 1024 / 1024} MB`); // smaller than maxSizeMB

  await uploadToServer(compressedFile); // write your own logic
} catch (error) {
  console.log(error);
}
```
