### ISSUE TITLE
getting black image after compression on iPhone Chrome (not safari???)

### ISSUE THREAD

**Issue by JordanDDisch** [Donaldcwl/browser-image-compression#169]
Device:
- iPhone SE 2nd gen
- chrome for iphone v 107.0.5304.101
- IOS 15.5

Steps to reproduce: 
- open chrome for iphone
- go to the demo site for this package https://donaldcwl.github.io/browser-image-compression/example/basic.html
- download this image: https://effigis.com/wp-content/uploads/2015/02/Airbus_Pleiades_50cm_8bit_RGB_Yogyakarta.jpg (satellite image 41mb jpeg) 
- upload that image with the latest package version and default settings in the package demo site
- download the image
- it comes back as a black image

You can try those same steps for iPhone Safari and not have that issue (also not an issue on Macbook Pro M1 using chrome 107.0.5304.110) 🤷 

Also to note not an issue on Android phone (Android v9, chrome 107.0.5304.105)

iPhone Chrome:
![IMG_4043](https://user-images.githubusercontent.com/4076759/202318423-6e0904d1-40b7-49ad-b62b-d5a73421525d.jpg)

iPhone Safari:
![IMG_4044](https://user-images.githubusercontent.com/4076759/202318986-b80867d8-ad36-4420-b285-bac0d0a5df6d.PNG)

**Comment by JordanDDisch** [comment]
it looks like chrome for IOS doesn't support very large canvas sizes. Used canvas-size github library to check and it looks like chrome for iphone only gives you a max canvas size of 4,096 x 4,096. Safari does also give a similar canvas size 4,096 x 4,096 but the allowed width and height are much larger then chrome for iphone.

**Comment by beyondlevi** [comment]
@Donaldcwl, thank you for your great work and indispensable tool. Any predictions on when the new version that fixes these issues with iOS 16.3 will be released?

**Comment by Donaldcwl** [comment]
@beyondlevi Will release it in a few days. Thanks.
