### ISSUE TITLE
Unable to Compress "TIFF" & "TIF" Images

### ISSUE THREAD

**Issue by hellonivas** [Donaldcwl/browser-image-compression#173]
Tried to upload and compress the tiff image in the given demo link. but getting an alert popup as "undefined"
Demo link: https://donaldcwl.github.io/browser-image-compression/example/basic.html

![image](https://user-images.githubusercontent.com/4760013/209764228-11ac1c48-5e68-4a00-861b-17915d754d36.png)

**Comment by Donaldcwl** [comment]
IFF image is currently not supported. You may use some TIFF decoders to load the image as a blob object and then input into this library.
