### ISSUE TITLE
Compression even when within parameters

### ISSUE THREAD

**Issue by MentalGear** [Donaldcwl/browser-image-compression#179]
I was wondering it it's intentional that file compressions still proceeds even if a file, for example 500kb, 256px resultion max, is within the parameters defined in options.
```js
const options: Options = { 
  maxSizeMB: 2, 
  maxWidthOrHeight: 1024,  
}
```

Or is there a switch to change this behavior ?

**Comment by Donaldcwl** [comment]
TLDR: this library won't directly return the input file as the output under any circumstances

This library does more than just compression in the process such as "fixing" orientation from EFIX metadata.
Image files will always be loaded into Canvas at the beginning. If the canvas file size does not exceed the maxSizeMB, the canvas file will be returned.

Currently, there is no plan to add a switch for this behavior.

**Comment by MentalGear** [comment]
May I ask what other things it does, maybe you could point me to the file where it checks what needs to be done like EXIF ?
(Also a big THX for this super useful and easy to use library !)

**Comment by Donaldcwl** [comment]
The file will be different once it is loaded into Canvas. The file size may change after it is "exported" back to a file.
(https://github.com/Donaldcwl/browser-image-compression/blob/b1959e08720074eb1dedff8e47d036911acd4cf2/lib/image-compression.js#L55-L92)

Currently, it only checks for EXIF orientation change rotates it if necessary.
(https://github.com/Donaldcwl/browser-image-compression/blob/b1959e08720074eb1dedff8e47d036911acd4cf2/lib/image-compression.js#L65-L68)

If the file size exceeds the maxSizeMB, the compression will kick in.
(https://github.com/Donaldcwl/browser-image-compression/blob/b1959e08720074eb1dedff8e47d036911acd4cf2/lib/image-compression.js#L95-L126)
