### ISSUE TITLE
Node version

### ISSUE THREAD

**Issue by pablohpsilva** [Donaldcwl/browser-image-compression#185]
I understand this module has a limitation between node versions 14 and 16. Would it be possible to extend it to 18?

```
error browser-image-compression@2.0.1: The engine "node" is incompatible with this module. Expected version ">=14 <=16". Got "18.0.0"
```

**Comment by m0hamdan** [comment]
I have the same issue as above. I'm using node v 18.*

**Comment by Donaldcwl** [comment]
Please upgrade to v2.0.2. Thanks.

**Comment by pablohpsilva** [comment]
Thank you @Donaldcwl
