### ISSUE TITLE
File is Incorrectly Typed as File

### ISSUE THREAD

**Issue by vantaboard** [Donaldcwl/browser-image-compression#186]
I believe the return is typed incorrectly.

Upon logging, you can see it is referred to as a `Blob`. It has all of the correct properties, but at some point during this transaction, it drops `type`, and I kept getting errors related to `type` being `undefined` despite it being in there as a property. Once I began treating is a `Blob` without the properties of my `File` it worked. I'm wondering what this is caused by.
![image](https://user-images.githubusercontent.com/86866786/228185494-1649b285-1ab7-4842-87a2-0e8096609133.png)

**Comment by Donaldcwl** [comment]
It has intentionally been changed to "Blob" due to compatibility with browsers.

Details in: https://github.com/Donaldcwl/browser-image-compression/blob/d933bc8e483a9853ed2b57338e035e8c45e40dc7/lib/utils.js#L22
