### ISSUE TITLE
Async/await not working as expected

### ISSUE THREAD

**Issue by pmourelle** [Donaldcwl/browser-image-compression#2]
Hi there. I'm trying to use browser-image-compression with async/await, not being able to do it.
I wrapped the call to have it resolve by its own and having a cleaner code as below (showing relevant parts).

```javascript
const myImageCompressor = async (val, maxSizeMB, maxWidthOrHeight) => {
  const result = await imageCompressor(val, maxSizeMB, maxWidthOrHeight);
  return result;
};
```

Then I'm using it as:
```javascript
for (let item of Object.entries(payload)) {
  let [key, val] = item;
  ...
  const maxMB = 1,      // max MBs
  maxSize = 1200; // max Size rescale
  val = myImageCompressor(val, maxMB, maxSize);
  ...
}
```
Problem is that `val` doesn't have a File but a still unsolved Promise. Is this a bug or there's anything wrong in the code above?

**Comment by kdalkafoukis** [comment]
@pmourelle I think you miss `await` to `val =  myImageCompressor(val, maxMB, maxSize);`

**Comment by Donaldcwl** [comment]
@pmourelle
@kdalkafoukis is right, your async function "myImageCompressor " return a promise which needs to be "await" for the result.

**Comment by pmourelle** [comment]
Thanks guys. I'd done some workaround on overall code. I'll try some clean up on this next week.
