### ISSUE TITLE
Why does it take longer in my app than in the demo

### ISSUE THREAD

**Issue by AlejandroGutierrezB** [Donaldcwl/browser-image-compression#206]
Hi, 

Why same image and same config,  take under 1 sec to compress in your demo  and over 20 secs in my nextjs app.

I notice the converter is loaded from the cdn, but why? I want it to be bundled in my app

Am I missing something

```
import imageCompression from 'browser-image-compression';


....


try {
        console.time('imageCompression');

        const file = await imageCompression.getFilefromDataUrl(uri, asset.fileName || 'image', Date.now());
        const compressedFile = await imageCompression(file, {
          maxSizeMB: 1,
          maxWidthOrHeight: 1024,
        });
        const base64 = await imageCompression.getDataUrlFromFile(compressedFile);

        console.timeEnd('imageCompression');
      } catch (error) {
        console.error('error', error);
      }
      
      
....
      ```

**Comment by mrbotmd** [comment]
I think compression speed depend on what image type you are trying to compress. 
For near instant compression add fileType: 'image/jpeg' to your options.
Like this
`{
          maxSizeMB: 1,
          maxWidthOrHeight: 1024,
 fileType: 'image/jpeg'
        }`

**Comment by JulienLecoq** [comment]
Wow, why does this makes so much of a difference? I got the same issue than @AlejandroGutierrezB but after setting ``fileType: 'image/jpeg'``, it was day and night. 

I have a MacBook Pro M2 Max and it was soo long without the filetype set to 'image/jpeg'. I didn't take a look at the duration but I think it was something like 15/20 seconds too and now it is near instant even when compressing big files with a strong compression.
