### ISSUE TITLE
SecurityError on load in IE10

### ISSUE THREAD

**Issue by david-wrt** [Donaldcwl/browser-image-compression#28]
When attempting to use the library even just to run without web workers enabled in IE10, I am getting a SecurityError, with the following pointer on page load: 
browser-image-compression.min.js, line 12 character 5652

This appears to point to: return new Worker(URL.createObjectURL(new Blob(["(

Due to this error, imageCompression is undefined later when I attempt to invoke it and the call obviously fails.

**Comment by Donaldcwl** [comment]
It should be fixed in version v1.0.7
