### ISSUE TITLE
Missig file extension "mjs".

### ISSUE THREAD

**Issue by pApApAw** [Donaldcwl/browser-image-compression#3]
Import package in react but i got this `linting error` Missing file extension "mjs" for "browser-image-compression".

**Comment by Donaldcwl** [comment]
@pApApAw Sorry for my late reply, can you provide more detail such as react version, linting package, etc. If possible, screenshots would also help in solving the issue. Thanks.

**Comment by Donaldcwl** [comment]
Inactive issue
