### ISSUE TITLE
Feature Request: Progress Update

### ISSUE THREAD

**Issue by gravitymedianet** [Donaldcwl/browser-image-compression#32]
It would be great if there was a prop or method to update the progress of compression.

In my app, I uploaded a 10 mb file and compressed it down to 2.5 mb. It took about 2 seconds. I had no way to show progress. What I ended up doing is showing an animated progress bar that is 100%. But it would be nice to show the compression progress as an increasing progress bar.

**Comment by Donaldcwl** [comment]
The feature is added in version v1.0.7
