### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by Madeorsk** [Donaldcwl/browser-image-compression#47]
When I try to use imageCompression, I get a very strange error.

![Thrown error](https://user-images.githubusercontent.com/5805468/76944884-0d2b1600-6902-11ea-8a9d-2034ea5cdf86.png)

My code is the easiest I can write:

```javascript
imageCompression(file, {
	maxSizeMB: 10,
}).then((compressedFile) => {
	console.log("ok");
}).catch((error) => {
	console.log(error);
});
```

EDIT: Looks like it happens only on a specific image file... I think that it's corrupted which is very strange because all other softwares can open it.

**Comment by Donaldcwl** [comment]
Can you upload that image for us to reproduce it?

**Comment by Madeorsk** [comment]
I can display it in [Eye Of Gnome](https://wiki.gnome.org/Apps/EyeOfGnome), sometimes in Firefox / Chromium (it doesn't work here but in some cases the image was shown). I think you don't need to take my issue in account as it is not a normal state for an image file.

![something is broken?](https://user-images.githubusercontent.com/5805468/77260157-8fab3100-6c86-11ea-89a1-afe682bfce48.png)

**Comment by Madeorsk** [comment]
Oh OK I've just found why. When I tried to open this image in Glimpse (~GIMP), it asked me how to import it as an SVG file. So I opened it in an editor and... It is an SVG file! I don't know why the extension was PNG... Sorry!
