### ISSUE TITLE
Image resolution

### ISSUE THREAD

**Issue by nathanmichel** [Donaldcwl/browser-image-compression#5]
Hi,

I used this code :
`imageCompression(inputFile, {maxSizeMB: 1, maxWidthOrHeight: 720, useWebWorker: true})`

But the resulted dimension of the picture is 3400x2267 (the original dimension being 5184x3456)

The size is what's expected.

I have tried to remove maxSizeMB and using maxWithOrHeight only but the final image keep the original dimension AND the final file weight is much bigger than the original. The size of the original image is 4mo the final image 11mo.

Thank you.

**Comment by Donaldcwl** [comment]
Hi,
Can you upload the image so that I can have to look at the issue?
Thanks.

**Comment by nathanmichel** [comment]
Hi

This is the original image : https://www.dropbox.com/s/eahbut73r92qqwl/beach-by-the-sea-clouds-946343.jpg?dl=0

**Comment by Donaldcwl** [comment]
@nathanmichel Thanks for reporting this issue
I have fixed it and released a new version v1.0.1
