### ISSUE TITLE
Exif orientation support broken with iOS 13.4.1 and Safari 13.1 Desktop

### ISSUE THREAD

**Issue by ssmithereens** [Donaldcwl/browser-image-compression#52]
In iOS 13.4.1 (released a few days ago) as well as Safari 13.1 desktop, the EXIF orientation value is no longer being handled properly, and the compressed image that is output will not have the correct orientation.

The easiest way to reproduce this is to go to the demo site https://donaldcwl.github.io/browser-image-compression/example/basic.html using a Safari or Chrome browser on a device running iOS 13.4.1 and attempt to upload the attached image. This image has orientation EXIF value of 3 (rotated 180 degrees).

The demo page will return the image rendered upside down. However, the same image on a device not running iOS 13.4.1 will return the image rendered with the proper orientation.

![IMG_2119](https://user-images.githubusercontent.com/36458824/79154490-9fa5c480-7d9d-11ea-852c-e078ca0a712f.JPG)

<img width="386" alt="ios 13 3" src="https://user-images.githubusercontent.com/36458824/79154598-d11e9000-7d9d-11ea-9c44-05074710a6aa.png">

![ios 13 4 1](https://user-images.githubusercontent.com/36458824/79154601-d1b72680-7d9d-11ea-9e8e-ea9d252d1f07.png)

**Comment by ssmithereens** [comment]
I believe that this change in Webkit (used by Safari) is the source of the problem: https://bugs.webkit.org/show_bug.cgi?id=201123

The required action for this library would be to ignore the EXIF orientation value when on Safari 13.1 (or later).

**Comment by bbss** [comment]
Echo this issue on chrome ios and android.
