### ISSUE TITLE
Image larger than MaxSizeMB

### ISSUE THREAD

**Issue by innominata** [Donaldcwl/browser-image-compression#62]
Not sure if this is an bug or a limitation of PNG files, but with MaxSizeMB set to 2, my 8MB PNG file is output at 5MB.
![leaf](https://user-images.githubusercontent.com/4099099/83316666-3d385300-a27b-11ea-92d3-8c70b0aa2393.png)

**Comment by Donaldcwl** [comment]
@innominata This lib used an iterative approach to compress the image. The default number of iteration is 10. If you expect to compress a very large image, you can increase the maximum number of iteration by setting the parameter 'maxIteration' in the options. Such as:
```js
imageCompression(file, {maxSizeMB: 2, maxIteration: 50})
```
