### ISSUE TITLE
Import the package in Angular

### ISSUE THREAD

**Issue by ynyz2003** [Donaldcwl/browser-image-compression#63]
Thanks for the contribution. 
A quick question. After I installed this package using npm install, how do I import in Angular.

I tried import imageCompression from 'browser-image-compression'; but imageCompression doesn't exist in browser-image-compression.

Any thoughts?

**Comment by Donaldcwl** [comment]
@ynyz2003 You may want to take a look at the example Angular app at:
https://github.com/Donaldcwl/browser-image-compression/blob/master/example/Angular%20App/src/app/image-compress/image-compress.component.ts

**Comment by johnfewell** [comment]
Hi there, I've looked at the example Angular app, and I'm getting this error message: `Module '"node_modules/browser-image-compression/dist/browser-image-compression"' can only be default-imported using the 'allowSyntheticDefaultImports' flag`
I have set `"allowSyntheticDefaultImports": true,` but the error persists.

**Comment by abnersouza** [comment]
Same Here

**Comment by abnersouza** [comment]
Same 

> Hi there, I've looked at the example Angular app, and I'm getting this error message when I try to use it in my own project: `Module '"node_modules/browser-image-compression/dist/browser-image-compression"' can only be default-imported using the 'allowSyntheticDefaultImports' flag`
> I have set `"allowSyntheticDefaultImports": true,` but the error persists.

Same issue here, have you figure out?

**Comment by johnfewell** [comment]
> Same
> 
> > Hi there, I've looked at the example Angular app, and I'm getting this error message when I try to use it in my own project: `Module '"node_modules/browser-image-compression/dist/browser-image-compression"' can only be default-imported using the 'allowSyntheticDefaultImports' flag`
> > I have set `"allowSyntheticDefaultImports": true,` but the error persists.
> 
> Same issue here, have you figured it out?

I used [Compressorjs](https://github.com/fengyuanchen/compressorjs) instead. 
Great library!

**Comment by felipeaf** [comment]
Same here. If i change import to `import * as imageCompression from 'browser-image-compression';`it compiles, but when it should run the function i got an error: 
```
core.js:6014 ERROR TypeError: browser_image_compression__WEBPACK_IMPORTED_MODULE_5__ is not a function
    at FileReader.reader.onload (reportar-problemas-novo.component.ts:182)
    at ZoneDelegate.invoke (zone-evergreen.js:359)
    at Object.onInvoke (core.js:39699)
    at ZoneDelegate.invoke (zone-evergreen.js:358)
    at Zone.runGuarded (zone-evergreen.js:134)
    at FileReader.<anonymous> (zone-evergreen.js:118)
defaultErrorLogger @ core.js:6014
handleError @ core.js:6066
next @ core.js:40558
schedulerFn @ core.js:35336
__tryOrUnsub @ Subscriber.js:185
next @ Subscriber.js:124
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:35298
(anonymous) @ core.js:39738
invoke @ zone-evergreen.js:359
run @ zone-evergreen.js:124
runOutsideAngular @ core.js:39572
onHandleError @ core.js:39735
handleError @ zone-evergreen.js:363
runGuarded @ zone-evergreen.js:137
(anonymous) @ zone-evergreen.js:118
load (async)
set @ zone-evergreen.js:1361
onFileChange @ reportar-problemas-novo.component.ts:171
eval @ ReportarProblemasNovoComponent.html:33
handleEvent @ core.js:43993
callWithDebugContext @ core.js:45632
debugHandleEvent @ core.js:45247
dispatchEvent @ core.js:29804
(anonymous) @ core.js:42925
(anonymous) @ platform-browser.js:2668
invokeTask @ zone-evergreen.js:391
onInvokeTask @ core.js:39680
invokeTask @ zone-evergreen.js:390
runTask @ zone-evergreen.js:168
invokeTask @ zone-evergreen.js:465
invokeTask @ zone-evergreen.js:1603
globalZoneAwareCallback @ zone-evergreen.js:1629
```

The only way that i could use imageCompression with angular, and is a really bad sollution, was using an <script ...> tag in my html template file, instead of import in angular, and using global call like `window['imageCompression'](file, options)`

**Comment by felipeaf** [comment]
In the example  Visual Studio Code show this error, but ng build or serve works. To solve this i have to set this flag in tsconfig.json, in compilerOptions subobject:
```javascript
{
  //...
  "compilerOptions": {
    //...
    "allowSyntheticDefaultImports": true
  },
  //...
}
```
