### ISSUE TITLE
Include default quality level on options

### ISSUE THREAD

**Issue by NelsonReis** [Donaldcwl/browser-image-compression#64]
The default quality level is hard-coded to value 1 but if it could be surfaced to the options, it would allow to use a lower value for cases where it could be reduced.

On a specific case I have, from a 5MB file, the default compression (quality = 1) would set the file size to 872KB, as if quality=0.9 (perfectly fine for my case) it would be 234KB, almost 4 times smaller file size.

Is there any reason why this was never considered?

**Comment by Donaldcwl** [comment]
@NelsonReis Thanks for your question.
This lib used an iterative approach to compress the image.
The mentioned 'quality' is initially set to 1, but it will gradually decrease during the process.
You may see the implementation here:
https://github.com/Donaldcwl/browser-image-compression/blob/v1.0.11/lib/image-compression.js#L89

**Comment by NelsonReis** [comment]
Thanks @Donaldcwl , I understand that's the method used, but was trying to understand if it could also be an option to set the initial quality level optionally. That would allow for other ways to work with this lib. If that was acceptable, I could try to work on that and create a PR. Nice work, by the way.

**Comment by Donaldcwl** [comment]
@NelsonReis Setting initial quality level can improve the flexibility of the lib. However, as I remember, PNG files only accept quality equals 1. Will this option creates confusion to users?
May I ask your use case for setting initial quality?

**Comment by NelsonReis** [comment]
The use case I have is for clients on mobile (specially the ones with low bandwidth and less performant phones) to be able to upload images faster. That's why it would be a good thing to allow to start on a lower quality, that way it would be quicker on lower-end phones, and I assume the compromise on the quality.
You might be right on the PNG quality, and that could probably create some confusion among users, though.

**Comment by Donaldcwl** [comment]
#78
