### ISSUE TITLE
`maxSizeMB` is violated.

### ISSUE THREAD

**Issue by ratulSharker** [Donaldcwl/browser-image-compression#68]
When i provide following configuration

```
const options = { 
  maxSizeMB: 0.029,          // 29Kb
  maxWidthOrHeight: 1080 //
};
```

Entering [this](https://upload.wikimedia.org/wikipedia/commons/f/ff/Pizigani_1367_Chart_10MB.jpg) image (9.7Mb) causes the output file size to be 0.04 (40KB). 

I also checked the same configuration [Demo](https://donaldcwl.github.io/browser-image-compression/example/basic.html). Its also happening in Demo too.

Expected result.
> Maintain a image size within given `maxSizeMB` even of the maxWidthOrHeight needed to be decreased more and more proportionally.

**Comment by ratulSharker** [comment]
I peeked into the source code and found [this](https://github.com/Donaldcwl/browser-image-compression/blob/9fcc363eeec63c7ff044144cf98d5bb3a408201a/lib/image-compression.js#L38)

```
```

**Comment by Donaldcwl** [comment]
@ratulSharker Yes, you are right since the library takes an iterative approach.
In your case, you may want to increase the option `maxIteration`.
