### ISSUE TITLE
drawImageInCanvas method throws error in iPhone X because OffscreenCanvas is incompatible

### ISSUE THREAD

**Issue by HexMox** [Donaldcwl/browser-image-compression#7]
Hi, great jobs.

```js
// browser-image-compression.mjs
function drawImageInCanvas(e) {
  let n;
  const canvas =
    typeof OffscreenCanvas === 'function' ? new OffscreenCanvas(e.width, e.height) : document.createElement('canvas');
  const context = canvas.getContext('2d');
  console.log('>>>>>> drawImageInCanvas', canvas);
  console.log('>>>>>> drawImageInCanvas', context);
  return (
    (n =
      typeof OffscreenCanvas === 'function' ? new OffscreenCanvas(e.width, e.height) : document.createElement('canvas'))
      .getContext('2d')
      .drawImage(e, 0, 0, n.width, n.height),
    n
  );
}
```

new OffscreenCanvas(e.width, e.height).getContext('2d') get null when runs in iPhone X（iOS 12.1）.
Maybe u should check the return value of getContext method.

Poor English, feel free to correct.

**Comment by Donaldcwl** [comment]
Hi,
Do you still having this issue?

I just tested it on a IOS simulator(iPhone X IOS 11) and it is working fine.
![image](https://user-images.githubusercontent.com/11781337/53957972-c74a4800-411a-11e9-93e8-e846857f279a.png)

According to the can i use website, the OffscreenCanvas should be undefined in IOS safari.
https://caniuse.com/#feat=offscreencanvas

The "typeof OffscreenCanvas === 'function'" should evaluate as "false" and the code "document.createElement('canvas')" should be executed.

Would you mind to test it again to confirm the issue?

Thanks.

**Comment by HexMox** [comment]
Hi Donaldcwl, Thanks for your reply.
There may be a few differences between iOS simulator and iPhone.
I added fallback logic which will reports some error messages when occurs unexpected error.

**Comment by ccirene** [comment]
I have found this problem too.  and it only occurs on iphone x. 
![15_16_13__04_23_2019](https://user-images.githubusercontent.com/5291251/56561926-d1e17380-65da-11e9-8cec-6ba8214db2cd.jpg)

**Comment by Donaldcwl** [comment]
@ccirene Since I don't have a physical iPhone X and simulator doesn't reproduce the issue, can you try to debug for me?

what is the value of following statements:
```
console.log('is function?', typeof OffscreenCanvas === 'function')
console.log('new works?', new OffscreenCanvas(10, 10))
console.log('getContext works?', (new OffscreenCanvas(10, 10)).getContext('2d'))
console.log('drawImage is function?', (new OffscreenCanvas(10, 10)).getContext('2d').drawImage)
```

Thanks!

**Comment by ccirene** [comment]
HI, thank you for helping me.
It console.log as below.
"is function? true
new works? [object OffscreenCanvas]
getContext works? null
TypeError: null is not an object (evaluating 'new OffscreenCanvas(10,10).getContext("2d").drawImage')
"
it seems getContext('2d') doesn't work at iphone x

**Comment by Donaldcwl** [comment]
@ccirene Can you try this version of the library to see if it works on iPhone X?
[browser-image-compression.zip](https://github.com/Donaldcwl/browser-image-compression/files/3106845/browser-image-compression.zip)
