### ISSUE TITLE
post data: name="blob"

### ISSUE THREAD

**Issue by sadektouati** [Donaldcwl/browser-image-compression#72]
Hi,
When I set width the output filename is set to filename="blob" (chrome developer tools) if I don't set the width everything works as expected.

N.B I took your example code verbatim

![90658851_1690943881046763_805043150929264640_n](https://user-images.githubusercontent.com/6498750/85200087-c8de5600-b2f4-11ea-878a-f618bbbdfd46.jpg)
.

**Comment by Donaldcwl** [comment]
When adding a blob object into FormData, the default filename is `blob`. You need to put a third filename parameter if you want to change it:
`formData.append(name, value, filename)`

see more: https://developer.mozilla.org/en-US/docs/Web/API/FormData/append#append_Parameters
