### ISSUE TITLE
Feature Request: controllable "quality" field

### ISSUE THREAD

**Issue by ndanvers** [Donaldcwl/browser-image-compression#78]
Hello there and thank you for this wonderful package.

**Current Behavior:**
Within `image-compression.js`, the quality is set via:
`let quality = 1`

It is further affected in the case of a jpeg:
```
if (file.type === 'image/jpeg') {
      quality *= 0.95
    }
```

**Desired Behavior**
Ability to input a quality field in the options passed to browser-image-compressor, like so:
```
let options = {
        maxSizeMB: 2,
        maxWidthOrHeight: 2048, 
        quality: 0.5
}
```

**reasoning**
I believe that there are certain use cases where it would be extremely useful to have more control over this.

Thank you again

**Comment by Donaldcwl** [comment]
https://github.com/Donaldcwl/browser-image-compression/commit/1c34372ca3155cbace924155d0dfd1a03e77dbf3

**Comment by ndanvers** [comment]
Fantastic, thank you for this addition.
