### ISSUE TITLE
Update TypeScript types

### ISSUE THREAD

**Issue by jamiehaywood** [Donaldcwl/browser-image-compression#83]
Based on the Mozilla documentation - the File interface inherits from the Blob interface and therefore the union type is unnecessary.

The primary reason for raising this PR is I was receiving type errors in my code:

```
Type 'File | Blob' is not assignable to type 'File'.
  Type 'Blob' is missing the following properties from type 'File': lastModified, name
This change addresses this issue.
```

**Comment by Donaldcwl** [comment]
Thanks for your update!

**Comment by xegulon** [comment]
Why do I get a Blob object instead of a File one?
