### ISSUE TITLE
TypeError: URL.createObjectURL is not a function when I mock in jest

### ISSUE THREAD

**Issue by joshpitzalis** [Donaldcwl/browser-image-compression#9]

**Comment by Donaldcwl** [comment]
Please refer to [https://stackoverflow.com/questions/52968969/jest-url-createobjecturl-is-not-a-function](https://stackoverflow.com/questions/52968969/jest-url-createobjecturl-is-not-a-function)

**Comment by joshpitzalis** [comment]
Trying to run jest with browser-image-compression throws two errors.

The first is `ReferenceError: Worker is not defined`.

If you're using create-react-app you can stub workers globally by adding this to src/setupTests.js. https://github.com/facebook/jest/issues/3449

```
class Worker {
    constructor(stringUrl) {
      this.url = stringUrl;
      this.onmessage = () => {};
    }

    postMessage(msg) {
      this.onmessage(msg);
    }
  }

window.Worker = Worker;
```

The next error you'll get is ` TypeError: URL.createObjectURL is not a function`

add `global.URL.createObjectURL = jest.fn();` to the setupTests file and you're good to go.

Thanks @Donaldcwl
