### ISSUE TITLE
Image Properties gone

### ISSUE THREAD

**Issue by dhevanthareza** [Donaldcwl/browser-image-compression#93]
why my server dont receive image properties, so my server save it named blob and without format

**Comment by nicolaszwier** [comment]
same here. Trying to figure out the solution.

**Comment by Donaldcwl** [comment]
@dhevanthareza @nicolaszwier 
Thanks for using the library.

Here is an example showing how to handle file upload for your reference:
https://github.com/Donaldcwl/browser-image-compression/tree/4dcf0393674827a3ba2ba0edfbebfa37f4a9ac9b/example-express-server

This is the screenshot showing the request to the server and response from the server. The server can read the image properties such as `originalname` and `mimetype`:
![sample screenshot](https://raw.githubusercontent.com/Donaldcwl/browser-image-compression/4dcf0393674827a3ba2ba0edfbebfa37f4a9ac9b/example-express-server/screenshot.png)
